on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name:  Java version 14.0.x
      uses: actions/setup-java@v1
      with:
        java-version: 14.0.x

    - run: gradle build
      env:
        USERNAME: token
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
